### ISSUE TITLE
RFC-9580 related issues

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm-sequoia#87]
Hi,

I'm trying out OpenPGP v6 signatures with rpm and running into various issues:

1. pgp_verify_signature() doesn't handle v6 signatures in the "NOKEY" branch so it always fails with "Unsupported signature version". Looking at the RFC, it seems to be calculated the same way, but doing that for v6 results in "digest prefix mismatch" so there's something else going on.
2. _rpmDigestLength() is missing SHA3 variants
3. rpm fails to find a matching key even when present in the keyring. AFAICS what happens is that pgpDigParamsSignID() for the signature is returning the LAST 64bits of the subkey fingerprint, whereas pgpDigParamsSignID() for the key is returning the FIRST 64bits (as expected for v6, AFAICS). 

1 and 2 clearly need updating rpm-sequoia. With 3 I wouldn't rule out rpm-side issues. I tried poking around on both sides but didn't see anything immediately obvious.

This was with manual testing, I'll create rpm-side test cases next for reproducers, at any rate this stuff will require some further changes on rpm-side too.

**Comment by nwalfield** [comment]
Thanks for taking a look at this.  The port to `sequoia-openpgp` v2.0 was mostly about porting `rpm-sequoia` to the latest API; we didn't do any testing with v6 artifacts.  If you already have tests or artifacts that we could, that would be very helpful.

**Comment by pmatilai** [comment]
There are now commented out test-cases for 1 and 3 in https://github.com/rpm-software-management/rpm/pull/3757

If you prefer a key + signed package as separate artifacts attached here, just say so.

**Comment by pmatilai** [comment]
Here's also what I think is the relevant part of `RPM_TRACE=1 ./tools/rpmkeys -Kv --nodigest /tmp/hello-2.0-1.x86_64.rpm` using the test key from that PR:

```
_pgpPubkeyKeyID: pkt: &[] <- 0x519000035280
_pgpPubkeyKeyID: Key ID: 036824F0AC60AED6
_pgpPubkeyKeyID: keyid: &[] <- 0x7efe9a7147c0
_pgpPubkeyKeyID: -> success
_pgpPrtParams: entered
 _pgpPrtParams2: entered
  pgp_prt_params: pkts: &[] <- 0x519000035280
  pgp_prt_params: paramsp: &mut <- 0x7efe9a714720
  pgp_prt_params: PgpDigParams { obj, signid: buffer, userid: userid, }: returning 0x518000008480
 _pgpPrtParams2: -> success
_pgpPrtParams: -> success
_pgpPubkeyFingerprint: entered
_pgpPubkeyFingerprint: pkt: &[] <- 0x519000035280
_pgpPubkeyFingerprint: Fingerprint: 036824F0AC60AED6F1A3256F88190469F6D7255E3D8E41C577233AA03E0BB9D3
_pgpPubkeyFingerprint: -> success
_pgpPrtParamsSubkeys: entered
_pgpPrtParamsSubkeys: pkts: &[] <- 0x51900003ca80
_pgpPrtParamsSubkeys: subkeys: &mut <- 0x7efe9a6ad1c0
_pgpPrtParamsSubkeys: subkeys_count: &mut <- 0x7efe9a6ad1b0
_pgpPrtParamsSubkeys: Subkey: 6118ABE481C41473
_pgpPrtParamsSubkeys: dig: returning 0x518000008880
_pgpPrtParamsSubkeys: Got 1 subkeys
_pgpPrtParamsSubkeys: -> success
_pgpDigParamsSignID: entered
_pgpDigParamsSignID: dig: & <- 0x518000008880
_pgpDigParamsSignID: SignID: 6118ABE481C41473
_pgpDigParamsSignID: -> success
/tmp/hello-2.0-1.x86_64.rpm:
_pgpPrtParams2: entered
_pgpPrtParams2: lint_str: Option<&mut> <- 0x7efe9a6af160
 pgp_prt_params: pkts: &[] <- 0x50e00000d400
 pgp_prt_params: paramsp: &mut <- 0x50800000c158
 pgp_prt_params: PgpDigParams { obj, signid: buffer, userid: userid, }: returning 0x518000008c80
_pgpPrtParams2: -> success
_pgpDigParamsAlgo: entered
_pgpDigParamsAlgo: dig: & <- 0x518000008c80
_pgpDigParamsAlgo: -> success
_pgpDigParamsSignID: entered
_pgpDigParamsSignID: dig: & <- 0x518000008c80
_pgpDigParamsSignID: SignID: 0E00DF3ED2D7B65E
_pgpDigParamsSignID: -> success
_rpmDigestInit: entered
_rpmDigestInit: ctx: returning 0x5030000c0a30
_rpmDigestInit: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x5030000c0a30
_rpmDigestUpdate: data: &[] <- 0x7efe9a55caa0
_rpmDigestUpdate: -> success
_rpmDigestUpdate: entered
_rpmDigestUpdate: ctx: &mut <- 0x5030000c0a30
_rpmDigestUpdate: data: &[] <- 0x51e000009088
_rpmDigestUpdate: -> success
_rpmDigestDup: entered
_rpmDigestDup: ctx: & <- 0x5030000c0a30
_rpmDigestDup: -> success
_rpmDigestFinal: entered
_rpmDigestFinal: ctx: owned <- 0x5030000c0a30
_rpmDigestFinal: -> success
_pgpSignatureType: entered
_pgpSignatureType: dig: & <- 0x518000008c80
_pgpSignatureType: -> success
_pgpDigParamsSignID: entered
_pgpDigParamsSignID: dig: & <- 0x518000008c80
_pgpDigParamsSignID: SignID: 0E00DF3ED2D7B65E
_pgpDigParamsSignID: -> success
_pgpVerifySignature2: entered
_pgpVerifySignature2: sig: & <- 0x518000008c80
_pgpVerifySignature2: ctx: & <- 0x5030000c0e20
_pgpVerifySignature2: lint_str: Option<&mut> <- 0x7efe9a715e50
_pgpVerifySignature2: -> error: Failure: Unsupported signature version: 6
_pgpDigParamsSignID: entered
_pgpDigParamsSignID: dig: & <- 0x518000008c80
_pgpDigParamsSignID: SignID: 0E00DF3ED2D7B65E
_pgpDigParamsSignID: -> success
_pgpSignatureType: entered
_pgpSignatureType: dig: & <- 0x518000008c80
_pgpSignatureType: -> success
_pgpDigParamsAlgo: entered
_pgpDigParamsAlgo: dig: & <- 0x518000008c80
_pgpDigParamsAlgo: -> success
_pgpDigParamsAlgo: entered
_pgpDigParamsAlgo: dig: & <- 0x518000008c80
_pgpDigParamsAlgo: -> success
_pgpDigParamsVersion: entered
_pgpDigParamsVersion: dig: & <- 0x518000008c80
_pgpDigParamsVersion: -> success
    Header OpenPGP V6 Ed25519/SHA512 signature, key ID 0e00df3ed2d7b65e: BAD
    Header OpenPGP RSA signature: NOTFOUND
    Header OpenPGP DSA signature: NOTFOUND
    Legacy OpenPGP RSA signature: NOTFOUND
    Legacy OpenPGP DSA signature: NOTFOUND

```

The full signing subkey fingerprint here is 6118ABE481C414734BBAE43FDA248BBBA888E5C54029B7C00E00DF3ED2D7B65E, and as per my earlier comment, _pgpPrtParamsSubkeys() and the first call to _pgpDigParamsSignID() (on the key I guess) gives the bytes from the start of that (6118ABE481C41473, as AIUI is the expectation for v6 keys), but then other calls to _pgpDigParamsSignID() return the bytes from the end (0E00DF3ED2D7B65E). And so rpm doesn't find the key even if present, and it goes downhill from there. It *looks* to me like something on the sequoia-side, but could be something else too.
